# Generated by Django 2.2.17 on 2021-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register2App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user2',
        ),
    ]
