# Generated by Django 2.2.17 on 2021-02-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register2App', '0002_auto_20210219_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user2',
        ),
    ]
